---
title: "Postesia population analyses"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Karina J. Nielsen"
date: "Last compiled on `r format(Sys.time(), '%d %B %Y')`"
output:
   bookdown::html_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  fig.align = "left",
  fig.width = 8,
  fig.height = 11,
  dev = "png",
  cache = T)

# echo = FALSE means code will not print, by default
# cache = TRUE saves output results of all chunks so that they do not need to be rerun

```


```{r renv-start, include = FALSE}
#install.packages("renv")
#renv::init() # to initialize a new project-local environment with a private R library
#renv::restore() # to restore a project-specific library
```

```{r load packages using easypackages, include=FALSE}

#reference for renv workflow: https://rstudio.github.io/renv/articles/renv.html
my_packages <- c("knitr", "renv", "easypackages", "here", "ggthemes", "gridExtra", "tidyverse", "lubridate", "patchwork", "readxl", "survival", "survminer", "ranger", "condSURV", "ggplot2", "gtsummary", "flextable", "dplyr", "forcats", "bookdown", "googledrive", "googlesheets4", "lme4", "ggeffects", "sjPlot", "effects") 
# list of packages to be used in this Rmd file
# easypackages::packages(my_packages) 
# checks to make sure the packages needed are loaded and asks before installing to confirm install in the console window
easypackages::libraries(my_packages) # could be used in lieu of packages() if you already have the packages installed

```


```{r Confirm working directory for project, include = FALSE}
here::here() # use this to work with sub-directories less awkwardly and share projects across users/machines more easily.
```


```{r renv, include=FALSE}
#Run this to update snapshot of packages when you commit the file
renv::snapshot() 
#run as needed later in the project to capture required package versions
#NB must respond and affirms actions in console or you will see the spinning wheel....

```


```{r read in data, include=FALSE}

#read in data from googlesheet file
pop_url <- "https://docs.google.com/spreadsheets/d/1UU4ZVFNtGX9wPg8YrwcVHOKCASZERbLxHoL7GWC3Hos/edit#gid=395307144"
post_pop <- read_sheet(pop_url) # will ask for account access in console

rcrt_url <- "https://docs.google.com/spreadsheets/d/160mIskabBabveqxF0W2zl1yK8zn14p70LDkyHMIGi-g/edit#gid=1440943028"
post_rcrt <- read_sheet(rcrt_url) # will ask for account access in console

sz_bm_url <- "https://docs.google.com/spreadsheets/d/1PokCNlykLovQSwm9HJuXuVPyr-RSu7wY9DYiBPIJxRY/edit#gid=897390894"
post_sz_bm <- read_sheet(sz_bm_url) # will ask for account access in console

```

```{r wrangle}

post_sz_bm <- post_sz_bm %>%
  mutate(log_stipeD = log(post_sz_bm$stipeD)) %>%
  mutate(log_ww = log(post_sz_bm$ww)) %>%
  mutate(log_dw = log(post_sz_bm$dw))

post_pop <- post_pop %>%
  mutate(trim_all = factor(ifelse(post_pop$trim > 0, 1, 0))) %>%
  mutate (yr_f = factor(post_pop$yr)) %>% 
  mutate (site_code_f = factor(post_pop$site_code)) %>% 
  mutate(trim = factor(post_pop$trim))


post_rcrt <- post_rcrt %>%
  mutate(trim_all = factor(ifelse(post_rcrt$trim > 0, 1, 0))) %>%
  mutate (yr_f = factor(post_rcrt$yr)) %>% 
  mutate (site_code_f = factor(post_rcrt$site_code)) %>% 
  mutate(trim = factor(post_rcrt$trim))

```

```{r diam-ww-model}

#fit the model
dwmodel <- lm(log(post_sz_bm$ww)~ log(post_sz_bm$stipeD))

#view the output of the model
summary(dwmodel)

```


```{r diam-ww, fig.width = 6,  fig.height = 6, message=FALSE}

diam_ww <- ggplot(post_sz_bm, aes(x=log_stipeD, y=log_ww)) +
  geom_point( size=4, color="seagreen") +
  geom_smooth(method=lm, se=TRUE) +
  theme_few() 

diam_ww +
  labs(x = "log [stipe diameter (cm)]") +
  labs(y = "log [wet weight (g)]") +
  labs(title= "Stipe diameter at the base predicts wet weight")+
  labs(subtitle = "wet weight(g) = 17.6 + stipe diameter(cm)^2.7, r2 = 0.99")

```
```{r dw-ww-model}

#fit the model
dwwwmodel <- lm(post_sz_bm$dw~ post_sz_bm$ww)

#view the output of the model
summary(dwwwmodel)

```


```{r diam-ww, fig.width = 6,  fig.height = 6, message=FALSE}

dw_ww <- ggplot(post_sz_bm, aes(x=ww, y=dw)) +
  geom_point( size=4, color="seagreen") +
  geom_smooth(method=lm, se=TRUE) +
  theme_few()

dw_ww +
  labs(x = "wet weight (g)") +
  labs(y = "dry weight (g)") +
  labs(title= "Wet weight predicts dry weight")+
  labs(subtitle = "dry weight(g) = -0.01 + 0.12*wet weight(g), r2 = 0.98")

```
```{r diam-dw-model}

#fit the model
ddwmodel <- lm(log(post_sz_bm$dw)~ log(post_sz_bm$stipeD))

#view the output of the model
summary(ddwmodel)

```


```{r diam-dw, fig.width = 5,  fig.height = 5, message=FALSE, include=TRUE}

diam_dw <- ggplot(post_sz_bm, aes(x=log_stipeD, y=log_dw)) +
  geom_point( size=2, color="seagreen") +
  geom_smooth(method=lm, se=TRUE) +
  theme_few() 

diam_dw +
  labs(x = "log [stipe diameter (cm)]") +
  labs(y = "log [dry weight (g)]") +
  labs(title= "Postelsia stipe diameter predicts biomass")+
  labs(subtitle = "dry weight(g) = 2.19 + stipe diameter(cm)^2.7, r2 = 0.99")

```

```{r summer-pop-decline-model}

#fit the model
summermodel <- lm(post_pop$aug~ post_pop$jun)

#view the output of the model
summary(summermodel)
#extract predicted values
pred.aug <- predict(summermodel, terms = c("jun"))

```

```{r popchangejun-aug, fig.width = 6,  fig.height = 6, message=F, warning=F, include =TRUE}

popJA <- ggplot(post_pop, aes(x=jun, y=aug)) +
  geom_point( size=2, color="seagreen") +
  geom_smooth(method=lm, se=TRUE) +
  theme_few() 

popJA +
  labs(x = "population size in June (2007-2009)") +
  labs(y = "population size in August (2007-2009)") +
  labs(title= "Population size declines 53% between June and August")+
  labs(subtitle = "August = 43 + 0.53*June, r2 = 0.86")
  


```
```{r trim-d}

bm_model <- lmer(augD ~ trim_all + yr_f + th +(1|site_code), data = post_pop)
summary(bm_model)
plot(bm_model)
ranef(bm_model)
coef(bm_model)
confint(bm_model)

bm_tab <- tbl_regression(bm_model)

bm_tab %>%
  add_global_p()%>% 
  bold_labels() %>% 
  italicize_levels()%>%
  as_flex_table()



```
```{r trim-d-table, fig.width = 6,  fig.height = 6, message=FALSE, Include =TRUE}

bm_tab <- tbl_regression(bm_model)

bm_tab %>%
  add_global_p()%>% 
  bold_labels() %>% 
  italicize_levels()%>%
  as_flex_table()


```
```{r plot-bm_model-fit, fig.width = 10,  fig.height = 4, }
bm_model_fit_yr <- ggpredict(bm_model, terms = c("th", "yr_f"))
bm_model_fit_trim <- ggpredict(bm_model, terms = c("th", "trim_all"))

bm_plot_1 <-  plot(bm_model_fit_yr) +
  theme_few()+
  labs(x="tideal height (ft) MLLW")+
  labs(y = "diameter (mm)")+
  labs(colour="year")+
  labs(title = "Modeled stipe diameter in August")

bm_plot_2 <- plot(bm_model_fit_trim) +
   theme_few()+
  labs(x="tideal height (ft) MLLW")+
  labs(y = "diameter (mm)")+
  labs(colour="trim")+
  labs(title = "Modeled stipe diameter in August")

bm_plot_1 + bm_plot_2

# ggplot(bm_model_fit, aes(x, predicted, color=group)) +
#   geom_line()+
#   facet_wrap(~facet)+
#   theme_few()+
#   labs(x="Tidal height (ft) MLLW")+
#   labs(y = "Predicted stipe diameter (mm)")+
#   labs (colour = "trim")

```


```{r trim-h, fig.width = 6,  fig.height = 6}
h_model <- lmer(augH ~ trim_all + yr_f + th + (1|site_code), data = post_pop)
summary(h_model)
plot(h_model)
ranef(h_model)
coef(h_model)
confint(h_model)


```


```{r trim-h-table, fig.width = 6,  fig.height = 6, message = FALSE }
h_tab <- tbl_regression(h_model)

h_tab %>%
  add_global_p()%>% 
  bold_labels() %>% 
  italicize_levels()%>%
  as_flex_table()

```

```{r plot-h-model-fit, fig.width = 8,  fig.height = 4 }
# h_model_fit <- ggpredict(h_model, terms = c("yr_f", "trim_all"))
# 
#  plot(h_model_fit) +
#   theme_few()+
#   labs(x="year")+
#   labs(y = "height (cm)")+
#   labs(colour="trim")+
#   labs(title = "Modeled stipe heights in August")
 
h_model_fit_yr <- ggpredict(h_model, terms = c("yr_f"))
h_model_fit_trim <- ggpredict(h_model, terms = c("trim_all"))

h_plot_1 <-  plot(h_model_fit_yr) +
  theme_few()+
  labs(x="year")+
  labs(y = "height (cm)")+
  labs(colour="trim")+
  labs(title = NULL)
 
 h_plot_2 <- plot(h_model_fit_trim) +
  theme_few()+
  labs(x="trim")+
  labs(y = NULL)+
  labs(colour="trim")+
  labs(title = NULL)
 
 h_plot_1 + h_plot_2
 

# ggplot(h_model_fit, aes(x, predicted, color=group)) +
#   geom_line()+
#   facet_wrap(~facet)+
#   theme_few()+
#   labs(x="Tidal height (ft) MLLW")+
#   labs(y = "Predicted stipe height (cm)")+
#   labs (colour = "trim")

```



```{r trim-pr, fig.width = 6,  fig.height = 6}

pr_model <- glmer(augPR ~ trim_all + yr_f + th + (1|site_code), data = post_pop, family=binomial)
summary(pr_model)
plot(pr_model)
ranef(pr_model)
coef(pr_model)


```

```{r trim-pr-table, message = FALSE, Include=TRUE}

pr_tab <- tbl_regression(pr_model, exp=TRUE)

pr_tab %>%
  add_global_p()%>% 
  bold_labels() %>% 
  italicize_levels()%>%
  as_flex_table()

```



```{r plot-pr-model-fit, fig.width = 8,  fig.height = 4, include=TREU }
pr_model_fit_yr <- ggpredict(pr_model, terms = c("yr_f"))
pr_model_fit_trim <- ggpredict(pr_model, terms = c("trim_all"))

pr_plot_1 <-  plot(pr_model_fit_yr) +
  theme_few()+
  labs(x="year")+
  labs(y = "percentage of population reproductive")+
  labs(colour="trim")+
  labs(title = NULL)
 
 pr_plot_2 <- plot(pr_model_fit_trim) +
  theme_few()+
  labs(x="trim")+
  labs(y = NULL)+
  labs(colour="trim")+
  labs(title = NULL)
 
 pr_plot_1 + pr_plot_2
 
# ggplot(pr_model_fit, aes(x, predicted, color=group)) +
#   geom_line()+
#   facet_wrap(~facet)+
#   theme_few()+
#   labs(x="Tidal height (ft) MLLW")+
#   labs(y = "Predicted stipe diameter (mm)")+
#   labs (colour = "trim")

```


```{r pop, fig.width = 6,  fig.height = 6}

pop_model <- lmer(jun ~ augLag + trim_all * yr_f + th + (1|site_code), data = post_pop)
summary(pop_model)
plot(pop_model)
ranef(pop_model)
coef(pop_model)
anova(pop_model)



```

```{r pop-table, message = FALSE, Include = TRUE}

pop_tab <- tbl_regression(pop_model)

pop_tab %>%
  add_global_p()%>% 
  bold_labels() %>% 
  italicize_levels()%>%
  as_flex_table()


```
```{r pop-plot, message = FALSE, Include = TRUE, fig.width = 8,  fig.height = 4}

pop_model_fit <- ggpredict(pop_model, terms = c("augLag", "trim_all", "yr_f"))

plot(pop_model_fit)+
  theme_few()+
  labs(colour="trim")+
   labs(x="August population size (prior year)")+
   labs(y = "June population size")+
  labs (title="Modeled recruitment")
  

# ggplot(pop_model_fit, aes(x, predicted, color=group)) +
#   geom_line()+
#   facet_wrap(~facet)+
#   theme_few()+
#   labs(x="August population size (prior year)")+
#   labs(y = "June population size")+
#   labs (colour = "trim")

```

